feature: 난이도에 따른 블럭 생성 확률 조정 기능
SW-Team2/se-team2-tetris pull request #36
Opened 2022-04-08 15:08 UTC by synnn0910

Issue: #35 

## 내용

이슈를 참고

## 작업사항

이슈를 참고

## 변경 전 / 변경 후
|변경 전|변경 후|
|---|---|
|<img src="" width="300" alt="" />|<img src="" width="300" alt="" />|
추후 Unit Test를 통해 확인

## 참고

2022-04-08 15:18 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +		for (int i = 0; i < VAR_TETROMINOS; i++) {
`VAR_TETROMINOS` 가 tetromino 모양의 총 개수인가요? 7로 초기화되있어서 유추했어요. 만약 맞다면 `NUMBER_OF_TETROMINOS` 로 작성하는게 의미가 와닿을 것같아요.

2022-04-08 15:38 UTC, ojj1123 requested changes

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +				mShapeANColorIndex = index;
`mShapeANColorIndex`은 어떤 변수인가요?

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +		for (int i = 0; i < VAR_TETROMINOS; i++) {
VAR_TETROMINOS 가 tetromino 모양의 총 개수인가요? 7로 초기화되있어서 유추했어요. 만약 맞다면 NUMBER_OF_TETROMINOS 로 작성하는게 의미가 와닿을 것같아요.

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  				if (TET_SHAPES[mShapeANColorIndex][col][row]) {
`TET_SHAPES`도 `TETROMINOS` 로 하는게 어떨까요? 어차피 테트로미노 배열이니까요.

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +	public static void setDifficulty(eDifficulty diff) {
`diff`의 의미가 모호합니다. diff라는 의미는 보통 `difference`의 축약형으로 쓰여요. `git diff`라는 command처럼요.
그냥 diffculty로 작성합시다.

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +	private static int mProbWeightArr[];
`prob`라는게 어떤의미인가요? 블럭이 출현하는 확률인가요?

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  		for (int col = 0; col < SHAPE_COL; col++) {
SHAPE_COL -> SHAPE_COLUMN 이렇게 해주세요.
col이나 row의 경우는 임시 변수이니까 i, j로 작성해도 무방할것 같은데 어떻게 생각하시나요?

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  	private int mShapeANColorIndex;
해당 변수명의 역할이 무엇인가요?

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  	public static final Position START_POS = new Position(-1, 3);
START_POS -> START_POSITION으로 바꿔주세요. 축약형은 되도록 지양하는 방향으로 가는게 어떨까요?

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  		COLOR_BLOCK_ARR[6] = new Block(purple);
`ARR`를 붙이는 것보다는 `COLOR_BLOCKS`으로 복수형으로 작성하는게 나아보여요.

2022-04-08 15:38 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  		for (int c = 0; c < SHAPE_COL; c++) {
아래에서는 col, row를 사용했는데 여기서는 c, r로 하셨네요. 통일감있게 c, r로 해주세요. for문에서 사용하는 임시 변수는 한 글자를 사용해도 무방합니다.

https://naver.github.io/hackday-conventions-java/#avoid-1-char-var

2022-04-08 16:05 UTC, ojj1123 approved these changes

2022-04-08 16:05 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  	public void deepCopy(Tetromino source) {
`setRandomShapeAndColor` 메소드 안에
`mShape[col][row] = COLOR_BLOCK_ARR[mShapeANColorIndex];` 이 있던데
이거랑
`deepCopy(Tetromino source)` 메소드랑 무슨차이인가요? 전자는 그냥 Block에 대한 reference 복사고 deepCopy도 내부를 보니까 같은 역할을 하던데, 설명부탁드립니다.
`mShapeANColorIndex = source.mShapeANColorIndex;` 이게 차이점이긴한데 `mShapeANColorIndex`이 변수의 역할이 정확히 파악이 안됩니다. `deepCopy`가 필요없는 메서드라면 삭제 부탁드립니다.

2022-04-08 16:06 UTC, ojj1123 requested changes

2022-04-08 16:06 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  	public void deepCopy(Tetromino source) {
setRandomShapeAndColor 메소드 안에
mShape[col][row] = COLOR_BLOCK_ARR[mShapeANColorIndex]; 이 있던데
이거랑
deepCopy(Tetromino source) 메소드랑 무슨차이인가요? 전자는 그냥 Block에 대한 reference 복사고 deepCopy도 내부를 보니까 같은 역할을 하던데, 설명부탁드립니다.
mShapeANColorIndex = source.mShapeANColorIndex; 이게 차이점이긴한데 mShapeANColorIndex이 변수의 역할이 정확히 파악이 안됩니다. deepCopy가 필요없는 메서드라면 삭제 부탁드립니다.

2022-04-08 16:24 UTC, ojj1123 requested changes

2022-04-08 16:24 UTC, ojj1123 commented on src/tetrisgame/TetrisGame.java
> +
블럭의 출현 확률을 바꾸는 함수는 따로 만드셨던데, 속도를 조절하는 부분도 똑같이 메소드로 만들어주세요.

2022-04-08 17:50 UTC, ojj1123 commented
Block class랑 Tetromino class랑 어떤 차이가 있는건가요?

2022-04-08 18:53 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
> +				mShapeANColorIndex = index;
1. 변경했습니다.
2. 오타입니다 mShpaeNColorIndex로 변경했습니다.

2022-04-08 18:53 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
> +		for (int i = 0; i < VAR_TETROMINOS; i++) {
테트로미노의 종류여서 VAR로 하였습니다.

2022-04-08 18:54 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
>  				if (TET_SHAPES[mShapeANColorIndex][col][row]) {
테트로미노의 모양(I,O,S,Z...)만을 나타냅니다

2022-04-08 18:57 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
> +	public static void setDifficulty(eDifficulty diff) {
1. num, temp, curr, prev와 같이 자주 쓰이고 그 의미가 명확하거나 지금 diff처럼 함수 시그니처등으로 뜻을 알 수 있는 변수는 짧은 변수명이 가독성에 더 좋다고 생각합니다.
2. 입력받은 난이도에 따라 weight를 변경하는 함수인데, 함수를 호출할 때 내부 구현이 어떤식으로 돼있는진 알 필요가 없습니다.

2022-04-08 19:01 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
> +	private static int mProbWeightArr[];
1. Probability입니다. 블럭 확률의 가중치를 나타냅니다. 각 배열의 요소의 비가 상대적인 확률을 나타냅니다. 
setDiffuculty함수와 setRandomShapeAndColor을 보시면 아실 수 있을 겁니다.
정확한 뜻을 나타내는 변수이름이 마땅히 떠오르지 않아 역할을 이해하면 뜻을 이해 할 수 있는 정도로 지었습니다. 추후에 문서화를 할 때 설명을 적는게 나을것 같습니다.
2. c-style선언도 표준에 속하지 않나요?

2022-04-08 19:03 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
>  		for (int col = 0; col < SHAPE_COL; col++) {
임시변수지만 i,j는 [i][j]인지 [j][i]인지 명확하지 않아 col row 나 c r로 표기했습니다

2022-04-08 19:05 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
>  	private int mShapeANColorIndex;
인스턴스의 모양과 색상 상수배열의 인덱스를 나타냅니다. mShape을 bool배열에서 Tile배열로 변경했으니 바꿔야 할 필요가 있겠네요.

2022-04-08 19:06 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
>  		COLOR_BLOCK_ARR[6] = new Block(purple);
arrList같은 컨테이너가 아닌 포인터를 사용할 땐 명시적으로 변수명에 써주는게 좋은거 같습니다

2022-04-08 19:14 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
>  	public void deepCopy(Tetromino source) {
https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html
clone부분을 보시면 이해가 되실거 같습니다.

2022-04-08 19:15 UTC, synnn0910 commented on src/tetrisgame/TetrisGame.java
> +
서로 다른 클래스에 구현돼 있습니다.

2022-04-08 19:17 UTC, synnn0910 commented
> Block class랑 Tetromino class랑 어떤 차이가 있는건가요?

Block클래스는 네모 블럭 하나만을 나타내고 테트로미노는
https://ko.wikipedia.org/wiki/%ED%85%8C%ED%8A%B8%EB%A1%9C%EB%AF%B8%EB%85%B8
이걸 나타냅니다.

Block클래스가 텍스처를 포함하게 변경돼서 Tile로 이름을 바꿧습니다. 화장실 타일할 때 그 네모타일을 생각하시면 됩니다,

2022-04-08 19:36 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +	public static void setDifficulty(eDifficulty diff) {
1. 변수가 짧으면 오히려 가독성이 안 좋아져요. `git diff`는 command 환경에서 사용하기 때문에 축약을 한거고,  협업할 때는 축약형 사용을 지양해야합니다. 일례로 시영님께서 작성하신 ENUM 변수인 COLL에 대해 처음에는 이게 무슨 의미인지 몰랐습니다. 한참뒤에야 코드를 읽고 이게 collision인지 알게 된거죠.
2. 내부 구현을 알고 못알고가 아니라 함수명이 함수의 역할을 표현하는가를 말씀드린거였어요.

2022-04-08 19:39 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  		for (int col = 0; col < SHAPE_COL; col++) {
https://naver.github.io/hackday-conventions-java/#avoid-1-char-var
임시 변수는 one char로 작성해도 상관없지만 어디에는 col이고 어디에는 c를 작성하면 일관성이 없지 않을까요?? 같은 사람이 작성한 코드에서도 다르다면 말이에요.

2022-04-08 19:41 UTC, ojj1123 commented on src/tetrisgame/TetrisGame.java
> +
이게 무슨말이죠?? 뭐가 서로 다른클래스라는거에요?

2022-04-08 19:50 UTC, ojj1123 commented on src/tetrisgame/TetrisGame.java
> +
이해했어요!

2022-04-08 19:57 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
>  		COLOR_BLOCK_ARR[6] = new Block(purple);
자바에는 포인터 개념이 없습니다. 참조일 뿐이죠. 그리고 "좋은 것 같다"라고 말씀하셨는데, 경험적인 부분 물론 중요하지만 어떤 컨벤션을 많이 사용한다는 자료 등을 제시해주는게 더 신뢰가 있습니다.

2022-04-08 20:01 UTC, ojj1123 commented on src/graphics/screens/GameScreen.java
>  public class GameScreen extends Screen {
`TetrisGame.java`에서 그려주던 뷰를 `GameScreen.java`로 옮기 신거 맞죠? 저도 그렇게 하자고 말씀드리려고 했는데 미리 해주신 것같아서요!

2022-04-08 20:07 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +	private static int mProbWeightArr[];
https://google.github.io/styleguide/javaguide.html#s4.8.3-arrays
google style에서는
> No C-style array declarations
라고 말하고 있네요. 저희 스타일 가이드 google로 통일하는거 아니었나요?

2022-04-08 20:14 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +		for (int i = 0; i < VAR_TETROMINOS; i++) {
테트로미노의 총 개수가 종류의 개수 아닌가요..! 처음 보는 축약형이었습니다.. 이런 이유로 축약형을 사용하지 말자고 제안한 거였어요. 가독성이 그렇게 좋아지지 않습니다..
`VAR`는 모르겠고, javascript 할 때 변수 선언할 때 `var` 라는 키워드를 사용하기는 합니다만.. 서로 무엇을 축약했는지 생각이 다를 수가 있어요..!

2022-04-08 20:45 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
> +	public static void setDifficulty(eDifficulty diff) {
1. 시그니처등으로 뜻을 알 수 있는 변수는 짧은 변수명이 가독성에 더 좋다고 생각합니다. 게임을 만드는데 Coll이 충돌을 뜻하는거 말고 헷갈릴게 있나요?
2. 예를 들어 RGB값을 얻어오는 RGB GetColor(String)함수가 있다고 할 때 이 함수 내부에서 RGB값을 saturate된 float값으로 가지고 있든 내부에서 감마보정을 하든 상관없이 사용하는 사람은 '색상을 string으로 입력하고 0~255에 RGBA채널의 값이 나온다' 만 알면 됩니다. 그런 연장선상에서 setDifficulty정도가 알맞은 이름입니다.

2022-04-08 20:46 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
> +	private static int mProbWeightArr[];
goolge로 통일하는건 금시초문이네요;;
처음에 정한 컨벤션에서 없는 부분은 재량껏 하는게 나은거 같아요.

2022-04-08 20:49 UTC, synnn0910 commented on src/tetrisgame/parts/Tetromino.java
>  		COLOR_BLOCK_ARR[6] = new Block(purple);
참조가 포인텁니다.
포인터 사용을 주의할 필요가 없었다면 unmanaged언어가 나오지도 않았겠죠

2022-04-08 20:52 UTC, synnn0910 commented on src/graphics/screens/GameScreen.java
>  public class GameScreen extends Screen {
네 맞습니당. JPanel에서 Paint메서드를 오버라이드하고 TetrisGame에선 프레임에 맞게 reprint메서드만 호출합니다

2022-04-09 03:32 UTC, ojj1123 commented on src/tetrisgame/parts/Tetromino.java
> +	public static void setDifficulty(eDifficulty diff) {
1. COLL 이 collision 일거라는거는 사람마다 다른거 아닌가요.. diff도 마찬가지고요. 각자 다른 언어를 했었기도 하고요. 서로 맞춰나가야죠. 코드를 작성한 사람 입장이 아니라 읽는 입장에서 말이에요
2. 의미가 그런거라면 전 괜찮습니다~

2022-04-09 03:51 UTC, ojj1123 requested changes

2022-04-09 03:51 UTC, ojj1123 commented on src/tetrisgame/parts/TileManager.java
> +        loadTex("tile_yellow");
texture를 tex로 축약해야하는 이유가 있을까요? 아래에서는 getTexture이라고 사용하셨고, 여기서는 loadTex라고 줄였는데, 특별히 줄인 이유가 있나해서요.

2022-04-09 08:52 UTC, ojj1123 commented
근데 확실히 블럭 모양을 바꾸니까 예쁘긴하네요~ 블럭을 아주 야무진걸 가져오셨네요ㅋㅋㅋㅋ

2022-04-09 10:59 UTC, synnn0910 commented
이거 괜찮나요? 이거저거 찾아보고 도트찍고 한 보람이 있군요.. 메뉴세팅 글씨체랑 애니메이션도 블럭느낌이랑 맞추면 좋을거같네용

2022-04-09 12:25 UTC, ojj1123 commented
뭐 툴 사용해서 만드신거에요? 아니면 그냥 이미지를 어디서 가져오신건가

2022-04-09 12:30 UTC, synnn0910 commented
https://pixlr.com/kr/x/ 여기서 그리거나 무료 사이트에서 다운 받았습니다

2022-04-09 15:25 UTC, synnn0910 commented
메인함수도  변경 되었습니다. WindowManager동작은 똑같고 좌,우,아래 이동은 꾹누르면 일정한 속도로 내려가고 다른 키들은 꾹 눌러도 한번만 동작하도록 하기위해 WindowManager의 keyRelease메서드 바디도 추가했습니다.

2022-04-10 04:50 UTC, ojj1123 commented on src/tetrisgame/parts/TexManager.java
> +        str.append(".png");
이렇게 하는 부분 있잖아요! `StringBuffer`를 사용한 이유가 있을까요?
String 클래스에 format이라는 method가 있어서 변수랑 String 붙이는 거는 어렵지 않아요!
```java
String path = String.format("../../res/background/%s.png", name);
```
이런식으로 하면 path를 만들 수 있는데 위에처럼 줄이는건 어떨까요!?

2022-04-10 04:50 UTC, ojj1123 commented on src/tetrisgame/parts/TexManager.java
> +    private TexManager() {
TexManager의 역할이 texture나 background image를 load해주는 역할인 것같은데, 맞나요? TexManager보다는 ImageMananger로 하면 부자연스럽나요?
`TexManager` 이게 필요한 이유가 잘 안와닿는데 설명해주세요!

2022-04-10 04:51 UTC, ojj1123 commented
해당 pr에서는 난이도에 따른 블럭생성확률, 속도 제어 까지 하고 테스트 하는 부분이랑 아이템 모드는 다른 이슈열어서 진행해주세요. 너무 많이 해버리면 어떤 걸 하고 있는지 파악이 안돼요!

2022-04-10 05:00 UTC, ojj1123 commented on src/tetrisgame/parts/TexManager.java
> +        str.append(".png");
```java
String path = String.format("../../res/tiles/%s.png", name);
```
이렇게 하면 줄일 수 있어요

2022-04-10 12:24 UTC, synnn0910 commented on src/tetrisgame/parts/TexManager.java
> +        str.append(".png");
이런게 있었군요..메모리 재할당,복사도 안일어나서 더 좋겠네요. 바꿔서 올리겠습니다

2022-04-10 12:33 UTC, synnn0910 commented on src/tetrisgame/parts/TexManager.java
> +    private TexManager() {
게임 오브젝트들에 쓰는 이미지들을 texture라고 하기도 하고 어떤 언어에선 Tex라는 키워드도 있어서.. 확실히 배경도 로드하니 ImageLoader가 나을거 같네요.
이미지가 필요할때 마다 파일스트림 열고 이미지를 로드하기보단 해쉬맵에 저장해두고 이름으로 불러오는게 성능에도 좋고 가독성도 좋다고 생각합니다. 필요한 이미지들이 다 정해지고 시간이 남으면 해쉬코드가 충돌하지 않게 만들고 해쉬코드를 Key로 만들어 버릴 생각입니다.

2022-04-10 12:34 UTC, synnn0910 commented
> 해당 pr에서는 난이도에 따른 블럭생성확률, 속도 제어까지 하고 테스트 하는 부분이랑 아이템 모드는 다른 이슈 열어서 진행해주세요. 너무 많은 것은 한꺼번에 해버리면 어떤 걸 하고 있는지 파악이 안돼요!

설정 불러오기 까지 하고 머지하려했는데 일단 오늘 머지하는게 나을까요?

2022-04-10 12:58 UTC, merged