Game component base
SW-Team2/se-team2-tetris pull request #46
Opened 2022-04-10 22:14 UTC by synnn0910

Issue: #45 

## 내용

이슈 내용 참고

## 작업사항

이슈 내용 참고

## 변경 전 / 변경 후
|변경 전|변경 후|
|---|---|
|<img src="" width="300" alt="" />|<img src="" width="300" alt="" />|
게임 작동은 같습니다.

## 참고

2022-04-11 01:38 UTC, synnn0910 commented
https://user-images.githubusercontent.com/100886249/162651015-17f0c255-3f0c-4c12-abc0-29becbd2538c.mp4

2022-04-11 01:39 UTC, synnn0910 commented
임시로 3줄만 지워도 아이템이 나오게 해놨습니다

2022-04-11 04:42 UTC, synnn0910 commented
https://user-images.githubusercontent.com/100886249/162666315-f002bb04-b997-4d32-bcd1-f49ee637b4d9.mp4

2022-04-15 13:51 UTC, synnn0910 commented
속도 저하 아이템 타일을 지우면 블럭 드랍 속도가 1 / (1-GAME_SPEED_ACCEL_UNIT) ^ 3 배 느려집니다
GAME_SPEED_ACCEL_UNIT는 10줄을 지웠을 때 드랍 속도가 빨라지는 단위입니다.

2022-04-15 14:32 UTC, ojj1123 commented
이거 bin 이거 무슨폴더들인가요? 엄청 많은데,, 빌드하면서 나온 파일들 같은데, 빌드 파일은 .gitignore 처리해주세요.

2022-04-15 15:54 UTC, ojj1123 commented
시영님 하나의 브랜치에서 많은 커밋을 가져가지 말아주세요. 작업량이 많으면 쪼개야합니다.

2022-04-15 16:29 UTC, synnn0910 commented
아이템 모드랑 이슈 링크한 겁니다. 한 작업 하고 다른 분들이 확인해 주실 때 까지 기다리면 다음 작업을 못해서요..

2022-04-15 16:31 UTC, ojj1123 commented
급한거라면 slack에 공지해주세요. 그리고 저는 github 메일로와서 계속 확인합니다. 부탁이니 슬랙에 현황같은거 공유해주세요. 아무도 시영님이 어떤 작업하는지 몰라요.

2022-04-15 16:35 UTC, ojj1123 commented
근데 시영님 말도 맞긴합니다. 이번에는 아이템모드 리팩터링한거랑 아이템 모드 개발하는 부분이라 어쩔수 없었을거에요!
원래는 다들 빠르게 확인하고 진행하는게 맞긴한데 ㅜㅜ 저라도 빨리 확인할테니까 슬랙에라도 공유해주세요.

2022-04-15 16:38 UTC, synnn0910 commented
네네 다음부턴 되도록 한꺼번에 올리고 올릴때 슬랙에 공유하겠습니다!

2022-04-15 16:41 UTC, ojj1123 commented
혹시 테스트 작업은 어떻게 하실 예정인가요? junit을 사용하는 것을 따로 공부하셔야 할 거 같아요..! 의존성 설치는 다 해놔서 사용법만 따로 하셔야겠어요!

2022-04-15 17:14 UTC, synnn0910 commented
색맹모드 까지 하고 주말동안 공부해보겠습니당

2022-04-16 17:47 UTC, ojj1123 requested changes

2022-04-16 17:47 UTC, ojj1123 commented on src/tetrisgame/component/tetromino/Tetromino.java
> +	private boolean collisionTest() {
관습적으로 test 코드를 짤 때 해당 class명 뒤에 "`*Test` 이런식으로 subfix를 붙입니다. 그래서 collitionTest는 테스트 코드라기 보다는 충돌을 check 해주는 method니까 `checkCollision`으로 바꾸는게 어떨까요? 제가 pr올린 db관련 테스트 코드를 보면 `*Test`이런 식으로 붙이있습니다. 참고로 intellij에서 테스트 코드 자동생성해주는 기능이 있는데 저렇게 생성해줍니다. #42 참고해주세용

2022-04-16 17:47 UTC, ojj1123 commented on src/tetrisgame/component/animation/LineRemovingAnim.java
> +        int col = -1;
col이 아니라 row입니다.

2022-04-16 17:47 UTC, ojj1123 commented on src/tetrisgame/component/tetromino/Tetromino.java
> +			for (int row = 0; row < SHAPE_ROW; row++) {
모든 반복문이 col이 바깥쪽이고 안쪽이 row던데 이 부분도 혹시 col이랑 row랑 헷갈리신건지 확인 부탁드려요. 물론 로직상에는 문제가 없을 수 있고, SHAPE_COL이랑 SHAPE_ROW랑 같은 4이기는 하나 작성한 사람이 다른 의미로 알고 있었다면 확인할 필요가 있어보입니다.

2022-04-16 17:47 UTC, ojj1123 commented on src/tetrisgame/component/tetromino/Tetromino.java
> +		mPubBoard = gb;
pubBoard 말고 다른 name으로 해주실 수 있나요? 아까 코드 같이보면서 pubBoard가 무엇인지 헷갈렸습니다! pub가 뭔지도 몰랐구요.(처음 보는 입장에서) 현재 실행되고 있는 board라면 currentBoard로 하거나 그냥 publicBoard라고 하면 어떨까요?

2022-04-16 17:47 UTC, ojj1123 commented on src/tetrisgame/component/animation/LineRemovingAnim.java
> +        switch (msg) {
LINE_REMOVE_0 ~ 19로 라인별로 하면 확장성이 떨어지니까 다른 방식으로 구현할 수 있을까요?

2022-04-17 18:25 UTC, synnn0910 commented
바로 바꿀 수 있는 부분부터 바꿨습니당. 금요일 전에 시간이 남으면 나머지 부분도 반영 하겠습니다. 
일단 잘 돌아가니 다른 요구사항을 구현하는게 먼저인거 같아서요

2022-04-17 18:30 UTC, ojj1123 commented
이미 사용하고 있는지는 모르겠지만, 변수명이나 함수명 같은거 바꾸실때 vscode의 refactoring 기능을 적극적으로 사용해주세요! 하나하나 바꾸거나 찾아서 하는 것보다 실수를 줄여줄 수 있습니당

요구사항 구현도 중요하지만, 실수나 오해의 여지가 있는 부분, 개선해야 하는 부분이 있으면 바로바로 바꿔주는 편이 좋다고 생각합니다! 기술부채(technical debt)가 생길 수도 있어서요.

2022-04-18 05:08 UTC, ojj1123 commented
@synnn0910 수정사항 다 했으면 merge 해주세요! 댓글같은거 확인했으면 이모지 부탁드립니다ㅜㅜ 사소한 거긴한데 소통할 때 이모지로 알 수 있는게 은근 많네요..!

2022-04-18 05:08 UTC, ojj1123 approved these changes

2022-04-19 01:28 UTC, merged